# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a3d84020de48e7c3612eaefc7642778569fbb19ea6c6fd38036cdd674ac0ee469aa65ab5d7fdc7f7f482953487d44ecaaf209f64f626864768be3b94e17f3a

test:
  secret_key_base: 7cc8e2fb7a4008913c106fb16657568b7d79b8dcd8276073c8e50b64c0d90e375d857b871aecf338dd61f9dd1f837a5bda17a8b3a5826043a5ead57cb8bd8939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
